name: Azure Functions Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/azure-functions-backend.yml"
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BA8970BAA2BA48D1BD6178F80CD37685 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E3D3ADB8EFEE483A9D70C8452C15E901 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_35160BC26DCB4DCB8D0B089172A38254 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: func-onelake-demo
          slot-name: Production
          package: api
          remote-build: true
          scm-do-build-during-deployment: true
          enable-oryx-build: true
